{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ascvd-from-fhir-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ascvd-from-fhir.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ascvd-from-fhir
                port: 
                  number: {{ $ingressPort }}
{{- end }}