apiVersion: v1
entries:
  ascvd:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-06-22T14:42:14.267971-05:00"
    description: A Helm Chart to deploy the Alvearie Atherosclerotic Cardiovascular Disease (ASCVD) service.  This service will calculate the risk of cardiovascular disease based on a small set of input parameters.
    digest: 6daf30138b5abf6bd221ef97cb47632d8d54ec0c28770f4b782406fb9195df89
    home: https://github.com/Alvearie/health-analytics/tree/main/ascvd
    keywords:
    - ibm
    - alvearie
    - ascvd
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: ascvd
    type: application
    urls:
    - ascvd-0.1.0.tgz
    version: 0.1.0
  ascvd-from-fhir:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-06-22T14:42:14.268409-05:00"
    description: A Helm Chart to deploy the Alvearie Atherosclerotic Cardiovascular Disease (ASCVD) data extraction (from FHIR) service.
    digest: 29530eae61178fa56c83f3bbf69095a5d686eda442c1d8084774caf1a129e3a1
    home: https://github.com/Alvearie/health-analytics/tree/main/ascvd-from-fhir
    keywords:
    - ibm
    - alvearie
    - ascvd
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: ascvd-from-fhir
    type: application
    urls:
    - ascvd-from-fhir-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-22T14:42:14.266111-05:00"
