# Default values for ascvd-from-fhir.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/ascvd-from-fhir
  pullPolicy: Always
  tag: 0.0.2
service:
  type: ClusterIP
  port: 5000

enabled: true

global:
  ingress:
    enabled: true
    class: REQUIRED-NOT-USED
         # IBM: public-iks-k8s-nginx
         # Azure: addon-http-application-routing
         # AWS: nginx
    subdomain: REQUIRED-NOT-USED

ingress:
  enabled: true
  class: REQUIRED-NOT-USED
       # IBM: public-iks-k8s-nginx
       # Azure: addon-http-application-routing
       # AWS: nginx
  subdomain: REQUIRED-NOT-USED