# Default values for ascvd-from-fhir.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: atclark/ascvd-from-fhir
  pullPolicy: Always
  tag: 0.0.1-SNAPSHOT
service:
  type: ClusterIP
  port: 5000

ascvd:
  url: http://ascvd:8080/

ingress:
  enabled: true
  class: 
         # IBM: public-iks-k8s-nginx
         # Azure: addon-http-application-routing
         # AWS: nginx
  host: