apiVersion: v1
kind: Service
metadata:
  name: {{ include "ascvd.fullname" . }}
  labels:
    {{- include "ascvd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Release.Name }}-ascvd
  selector:
    {{- include "ascvd.selectorLabels" . | nindent 4 }}